# Nichos candidatos: (grupo, término de búsqueda en español de México)
TERMS=[
 ("Dinero personal","control de gastos"),("Dinero personal","presupuesto personal"),("Dinero personal","ahorro tanda"),
 ("Dinero personal","control de deudas"),("Dinero personal","recordatorio de pagos"),("Dinero personal","calculadora de propinas"),
 ("Negocio chico","cuaderno de fiado"),("Negocio chico","cuentas por cobrar clientes"),("Negocio chico","cotizaciones pdf"),
 ("Negocio chico","control de inventario"),("Negocio chico","punto de venta tienda"),("Negocio chico","control de ventas diarias"),
 ("Negocio chico","recibos de pago"),("Negocio chico","catálogo de productos whatsapp"),("Negocio chico","pedidos por whatsapp"),
 ("SAT e impuestos","facturación cfdi"),("SAT e impuestos","calculadora isr resico"),("SAT e impuestos","declaración de impuestos sat"),
 ("Vender en línea","calculadora mercado libre"),("Vender en línea","inventario mercado libre"),("Vender en línea","etiquetas de envío"),
 ("Vender en línea","control de pedidos en línea"),
 ("Servicios y citas","agenda de citas"),("Servicios y citas","citas salón de belleza"),("Servicios y citas","control de pacientes consultorio"),
 ("Servicios y citas","administrar gimnasio socios"),("Servicios y citas","crm clientes"),("Servicios y citas","cotizador de eventos"),
 ("Fiestas y eventos","organizador de eventos"),("Fiestas y eventos","presupuesto de boda"),("Fiestas y eventos","invitaciones digitales"),
 ("Fiestas y eventos","lista de invitados"),("Fiestas y eventos","costeo de recetas"),
 ("Auto y casa","control de gasolina"),("Auto y casa","mantenimiento de auto"),("Auto y casa","verificación vehicular"),
 ("Auto y casa","hoy no circula"),("Auto y casa","administrar rentas propiedades"),("Auto y casa","gastos del hogar"),
 ("Auto y casa","calculadora de materiales construcción"),("Auto y casa","presupuesto de obra"),
 ("Trabajo por cuenta propia","control de ingresos repartidor"),("Trabajo por cuenta propia","gastos de chofer uber"),
 ("Trabajo por cuenta propia","control de horas trabajadas"),("Trabajo por cuenta propia","nómina empleados"),
 ("Salud","control de glucosa"),("Salud","presión arterial"),("Salud","recordatorio de medicamentos"),
 ("Salud","conteo de calorías"),("Salud","ayuno intermitente"),("Salud","rutina de gimnasio"),("Salud","embarazo semanas"),
 ("Salud","seguimiento de hábitos"),
 ("Escuela","tareas escolares"),("Escuela","calificaciones maestros"),("Escuela","planeación didáctica"),
 ("Escuela","examen de admisión"),("Escuela","vocabulario inglés"),
 ("Mascotas","cartilla de vacunación mascotas"),("Mascotas","cuidado de mascotas"),
 ("Día a día","lista de compras"),("Día a día","recetas de cocina"),("Día a día","control de servicios luz agua"),
 ("Día a día","agenda familiar"),("Día a día","tandas y cundinas"),
]
